"use client";
export const ContactData = [
  {
    id: 1,
    Avatar: "https://i.ibb.co/X3qh1Gr/pic1.jpg",
    banner: "https://i.ibb.co/5TJ0FN5/banner1.png",
    firstName: "Omar",
    lastName: "Faruq",
    email: "omar@gmail.com",
    address: "Street, Suite, City",
    position: "CEO",
    phone: "+880 147896",
  },
  {
    id: 2,
    Avatar: "https://i.ibb.co/R6t4Gfy/pic2.jpg",
    banner: "https://i.ibb.co/BNfLmfZ/banner2.png",
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice@gmail.com",
    address: "123 Main St, Apt 101, New York",
    position: "Manager",
    phone: "+880 147896",
  },
  {
    id: 3,
    Avatar: "https://i.ibb.co/WVm9JPC/pic3.jpg",
    banner: "https://i.ibb.co/YXstsQN/banner3.png",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    address: "456 Elm St, Suite 200, Boston",

    position: "Manager",
    phone: "+880 147896",
  },
  {
    id: 4,
    Avatar: "https://i.ibb.co/JxzWdwq/pic4.jpg",
    banner: "https://i.ibb.co/GpQDgHj/banner4.png",
    firstName: "Emily",
    lastName: "Smith",
    email: "emily.smith@example.com",
    address: "789 Oak St, Apt 303, San Francisco",

    position: "Manager",
    phone: "+880 147896",
  },
  {
    id: 5,
    Avatar: "https://i.ibb.co/v3s7qzZ/pic5.jpg",
    banner: "https://i.ibb.co/HK10ZXr/banner5.png",
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@example.com",
    address: "101 Pine St, Suite 100, Chicago",

    position: "Manager",
    phone: "+880 147896",
  },
  {
    id: 6,
    Avatar: "https://i.ibb.co/n8ntS3w/pic6.jpg",
    banner: "https://i.ibb.co/Qd30ySH/banner6.png",
    firstName: "Sophia",
    lastName: "Lee",
    email: "sophia.lee@example.com",
    address: "222 Cedar St, Apt 505, Los Angeles",
    position: "HR-Officer",
    phone: "+880 147896",
  },
  {
    id: 7,
    Avatar: "https://i.ibb.co/jkxVCby/pic7.jpg",
    banner: "https://i.ibb.co/r3j2WTN/banner7.png",
    firstName: "David",
    lastName: "Clark",
    email: "david.clark@example.com",
    address: "333 Maple St, Suite 400, Houston",
    phone: "+880 147896",
    position: "HR-Officer",
  },
  {
    id: 8,
    Avatar: "https://i.ibb.co/FK5h9t9/pic8.jpg",
    banner: "https://i.ibb.co/89qWx4g/banner9.png",
    firstName: "Emma",
    lastName: "Wilson",
    email: "emma.wilson@example.com",
    address: "444 Walnut St, Apt 606, Miami",
    phone: "+880 147896",
    position: "Business Analyst",
  },
  {
    id: 9,
    Avatar: "https://i.ibb.co/Z2V800b/pic9.jpg",
    banner: "https://i.ibb.co/5TJ0FN5/banner1.png",
    firstName: "James",
    lastName: "Garcia",
    email: "james.garcia@example.com",
    address: "555 Birch St, Suite 707, Seattle",

    position: "Business Analyst",
    phone: "+880 147896",
  },
  {
    id: 10,
    Avatar: "https://i.ibb.co/9HsKpxG/pic10.jpg",
    banner: "https://i.ibb.co/kKjsF0M/banner10.png",
    firstName: "Olivia",
    lastName: "Martinez",
    email: "olivia.martinez@example.com",
    address: "666 Willow St, Apt 808, Atlanta",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 11,
    Avatar: "https://i.ibb.co/NFXSJfZ/pic11.jpg",
    banner: "https://i.ibb.co/jk5dX4B/banner11.png",
    firstName: "Olivia",
    lastName: "Martinez",
    email: "olivia.martinez@example.com",
    address: "666 Willow St, Apt 808, Atlanta",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 12,
    Avatar: "https://i.ibb.co/kSrQkpd/pic12.jpg",
    banner: "https://i.ibb.co/60WGLzK/banner12.png",
    firstName: "Olivia",
    lastName: "Martinez",
    email: "olivia.martinez@example.com",
    address: "666 Willow St, Apt 808, Atlanta",

    phone: "+880 147896",
    position: "Driver",
  },

  {
    id: 111,
    Avatar: "https://i.ibb.co/T2591Q7/18.jpg",
    banner: "https://i.ibb.co/60WGLzK/banner12.png",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    address: "123 Main St, Anytown, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 112,
    Avatar: "https://i.ibb.co/Vp1c49X/19.jpg",
    banner: "https://i.ibb.co/jk5dX4B/banner11.png",
    firstName: "Alice",
    lastName: "Smith",
    email: "alice.smith@example.com",
    address: "456 Oak Ave, Othertown, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 113,
    Avatar: "https://i.ibb.co/547PXGy/20.jpg",
    banner: "https://i.ibb.co/kKjsF0M/banner10.png",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    address: "789 Elm St, Anothertown, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 114,
    Avatar: "https://i.ibb.co/KD10s8p/38.jpg",
    banner: "https://i.ibb.co/5TJ0FN5/banner1.png",
    firstName: "Emily",
    lastName: "Brown",
    email: "emily.brown@example.com",
    address: "321 Maple Ave, Yetanothertown, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 115,
    Avatar: "https://i.ibb.co/PgCLxKJ/37.jpg",
    banner: "https://i.ibb.co/89qWx4g/banner9.png",
    firstName: "Daniel",
    lastName: "Martinez",
    email: "daniel.martinez@example.com",
    address: "654 Pine St, Newtown, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 116,
    Avatar: "https://i.ibb.co/z6f61ZQ/36.jpg",
    banner: "https://i.ibb.co/r3j2WTN/banner7.png",
    firstName: "Sophia",
    lastName: "Taylor",
    email: "sophia.taylor@example.com",
    address: "987 Cedar Ave, Cityville, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 117,
    Avatar: "https://i.ibb.co/547PXGy/20.jpg",
    banner: "https://i.ibb.co/Qd30ySH/banner6.png",
    firstName: "Matthew",
    lastName: "Anderson",
    email: "matthew.anderson@example.com",
    address: "101 Oak St, Villageton, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 118,
    Avatar: "https://i.ibb.co/9YS4fpD/34.jpg",
    banner: "https://i.ibb.co/Qd30ySH/banner6.png",
    firstName: "Olivia",
    lastName: "Thomas",
    email: "olivia.thomas@example.com",
    address: "246 Walnut Ave, Countryside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 119,
    Avatar: "https://i.ibb.co/Sfh0VX6/33.jpg",
    banner: "https://i.ibb.co/HK10ZXr/banner5.png",
    firstName: "Ethan",
    lastName: "Hernandez",
    email: "ethan.hernandez@example.com",
    address: "369 Elm St, Riverside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 110,
    Avatar: "https://i.ibb.co/yNzMC7z/32.jpg",
    banner: "https://i.ibb.co/GpQDgHj/banner4.png",
    firstName: "Emma",
    lastName: "Garcia",
    email: "emma.garcia@example.com",
    address: "555 Maple Ave, Hilltop, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 111,
    Avatar: "https://i.ibb.co/pJfZ0TQ/31.jpg",
    banner: "https://i.ibb.co/YXstsQN/banner3.png",
    firstName: "Noah",
    lastName: "Rodriguez",
    email: "noah.rodriguez@example.com",
    address: "777 Cedar St, Lakeside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 122,
    Avatar: "https://i.ibb.co/Vp1c49X/19.jpg",
    banner: "https://i.ibb.co/BNfLmfZ/banner2.png",
    firstName: "Ava",
    lastName: "Lopez",
    email: "ava.lopez@example.com",
    address: "888 Oak Ave, Mountainside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 123,
    Avatar: "https://i.ibb.co/fpcc80L/29.jpg",
    banner: "https://i.ibb.co/5TJ0FN5/banner1.png",
    firstName: "Liam",
    lastName: "Perez",
    email: "liam.perez@example.com",
    address: "999 Elm St, Seaside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 124,
    Avatar: "https://i.ibb.co/jvgh7mR/28.jpg",
    banner: "https://i.ibb.co/60WGLzK/banner12.png",
    firstName: "Isabella",
    lastName: "Sanchez",
    email: "isabella.sanchez@example.com",
    address: "111 Pine Ave, Sunset, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 125,
    Avatar: "https://i.ibb.co/6BsTKZ7/27.jpg",
    banner: "https://i.ibb.co/jk5dX4B/banner11.png",
    firstName: "Mason",
    lastName: "Gonzalez",
    email: "mason.gonzalez@example.com",
    address: "222 Walnut St, Beachside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 126,
    Avatar: "https://i.ibb.co/GCkCZrW/26.jpg",
    banner: "https://i.ibb.co/5TJ0FN5/banner1.png",
    firstName: "Charlotte",
    lastName: "Ramirez",
    email: "charlotte.ramirez@example.com",
    address: "333 Oak Ave, Countryside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 127,
    Avatar: "https://i.ibb.co/1mVyMd4/25.jpg",
    banner: "https://i.ibb.co/89qWx4g/banner9.png",
    firstName: "William",
    lastName: "Torres",
    email: "william.torres@example.com",
    address: "444 Maple St, Hilltop, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 128,
    Avatar: "https://i.ibb.co/nMWv7vD/24.jpg",
    banner: "https://i.ibb.co/Qd30ySH/banner6.png",
    firstName: "Amelia",
    lastName: "Flores",
    email: "amelia.flores@example.com",
    address: "555 Elm Ave, Lakeside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 129,
    Avatar: "https://i.ibb.co/8MbJsQL/23.jpg",
    banner: "https://i.ibb.co/89qWx4g/banner9.png",
    firstName: "James",
    lastName: "Gutierrez",
    email: "james.gutierrez@example.com",
    address: "666 Cedar St, Mountainside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 220,
    Avatar: "https://i.ibb.co/pz4vZyz/22.jpg",
    banner: "https://i.ibb.co/Qd30ySH/banner6.png",
    firstName: "Evelyn",
    lastName: "Ortiz",
    email: "evelyn.ortiz@example.com",
    address: "777 Pine Ave, Seaside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 221,
    Avatar: "https://i.ibb.co/j6Yz2yp/21.jpg",
    banner: "https://i.ibb.co/YXstsQN/banner3.png",
    firstName: "Alexander",
    lastName: "Montgomery",
    email: "alexander.montgomery@example.com",
    address: "888 Oak St, Beachside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 222,
    Avatar: "https://i.ibb.co/547PXGy/20.jpg",
    banner: "https://i.ibb.co/5TJ0FN5/banner1.png",
    firstName: "Harper",
    lastName: "Barnes",
    email: "harper.barnes@example.com",
    address: "999 Maple Ave, Countryside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 223,
    Avatar: "https://i.ibb.co/Vp1c49X/19.jpg",
    banner: "https://i.ibb.co/BNfLmfZ/banner2.png",
    firstName: "Benjamin",
    lastName: "Mitchell",
    email: "benjamin.mitchell@example.com",
    address: "111 Elm St, Hilltop, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 224,
    Avatar: "https://i.ibb.co/T2591Q7/18.jpg",
    banner: "https://i.ibb.co/5TJ0FN5/banner1.png",
    firstName: "Elizabeth",
    lastName: "Perez",
    email: "elizabeth.perez@example.com",
    address: "222 Pine Ave, Lakeside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 225,
    Avatar: "https://i.ibb.co/8P3TWVv/17.jpg",
    banner: "https://i.ibb.co/60WGLzK/banner12.png",
    firstName: "Michael",
    lastName: "Roberts",
    email: "michael.roberts@example.com",
    address: "333 Oak St, Mountainside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 226,
    Avatar: "https://i.ibb.co/f2qvPFy/15.jpg",
    banner: "https://i.ibb.co/jk5dX4B/banner11.png",
    firstName: "Ella",
    lastName: "Turner",
    email: "ella.turner@example.com",
    address: "444 Maple Ave, Seaside, USA",

    phone: "+880 147896",
    position: "Driver",
  },
  {
    id: 227,
    Avatar: "https://i.ibb.co/8x2sgpC/16.jpg",
    banner: "https://i.ibb.co/5TJ0FN5/banner1.png",
    firstName: "Liam",
    lastName: "Phillips",
    email: "liam.phillips@example.com",
    address: "555 Elm St, Countryside, USA",
    phone: "+880 147896",
    position: "Electrician",
  },
  {
    id: 228,
    Avatar: "https://i.ibb.co/TYstQqz/14.jpg",
    banner: "https://i.ibb.co/Qd30ySH/banner6.png",
    firstName: "Avery",
    lastName: "Campbell",
    email: "avery.campbell@example.com",
    address: "666 Pine Ave, Hilltop, USA",
    phone: "+880 147896",
    position: "Electrician",
  },
  {
    id: 229,
    Avatar: "https://i.ibb.co/5nT3H6s/13.jpg",
    banner: "https://i.ibb.co/5TJ0FN5/banner1.png",
    firstName: "Sofia",
    lastName: "Parker",
    email: "sofia.parker@example.com",
    address: "777 Cedar St, Lakeside, USA",
    phone: "+880 147896",
    position: "Technician",
  },
  {
    id: 320,
    Avatar: "https://i.ibb.co/0MPhR3Q/39.jpg",
    banner: "https://i.ibb.co/jk5dX4B/banner11.png",
    firstName: "Jackson",
    lastName: "Young",
    email: "jackson.young@example.com",
    address: "888 Oak Ave, Mountainside, USA",
    phone: "+880 147896",
    position: "Technician",
  },
];
